substitutions:
  devicename: garage
  upper_devicename: Garage

<<: !include shared/esp8266.yaml

# Enable logging
logger:

debug:

output:
  - platform: gpio
    pin:
      number: D0
      inverted: true
    id: gpio_d0

light:
  - platform: binary
    id: led0
    output: gpio_d0
    internal: true

binary_sensor:
  - platform: gpio
    device_class: garage_door
    name: "Garage Door Left"
    pin:
      number: D1
      inverted: True
    filters:
      - delayed_on_off: 500ms
  - platform: gpio
    device_class: garage_door
    name: "Garage Door Right"
    pin:
      number: D2
      inverted: True
    filters:
      - delayed_on_off: 500ms
    on_press:
      then:
        - light.turn_off: led0
    on_release:
      then:
        - light.turn_on: led0
  - platform: status
    name: "${upper_devicename} Status"
    id: "${devicename}_status"

sensor:
  - platform: dht
    pin: D3
    model: DHT22_TYPE2
    temperature:
      name: ${upper_devicename} Temperature
      filters:
        - median:
            window_size: 5
            send_every: 5
    humidity:
      name: ${upper_devicename} Humidity
      filters:
        - median:
            window_size: 5
            send_every: 5
    update_interval: 20s
  - platform: wifi_signal
    name: "${upper_devicename} WiFi signal"
    id: "${devicename}_wifi_signal"
    update_interval: 60s
  - platform: uptime
    name: "${upper_devicename} Uptime"
    id: "${devicename}_uptime"
    update_interval: 60s
